
name: Merge branch rel-8.1 with rel-8.0
on:
  push:
    branches:
      - rel-8.0
jobs:
  merge-rel-8-1-with-rel-8-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Reset promotion branch
        run: |
          git fetch origin rel-8.0:rel-8.0
          git reset --hard rel-8.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-8-0/${{github.run_number}}
          title: Merge branch rel-8.1 with rel-8.0
          body: This PR was generated automatically to merge rel-8.1 with rel-8.0. Please review the changed files before merging to prevent any errors that may occur.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
